In [1]:
import pandas as pd
import numpy as np
import warnings
import boto3

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)

from __init__ import *

In [2]:
etl = ETLProcess(
    bucket_name="mega-dev-lake",
    prefix="RawData/indie_on_develop/",
    company="mgl",
    channel="showroom",
    year="2024",
    month="06",
)

In [4]:
etl.run()

,data_area_id,store_branch_name,store_branch_id,store_code,time_created,time_modified,order_create_date,order_create_hour,order_create_minute,order_id,transaction_id,invoice_id,employment_id,customer_id,order_number,order_issettled,order_status,order_total_product,order_total_quantity,order_subtotal,order_discount,order_total,order_transaction_price,order_voucher_payment,order_return_payment,order_cust_payment,promotion_id,promotion_title,promotion_description,product_id,product_item_id,product_variant_number,product_barcode,product_brand,product_sub_brand,product_item_model_group,product_price,product_quantity,product_subtotal,product_promotion_value,product_discount,product_transaction_price,product_cost,product_margin,product_cost_of_margin,product_total_cost,product_payment_contribution,product_voucher_payment,product_cust_payment,product_return_value,product_invoice_discount
0,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,170079543365488,2312000024734,0000083380,0900000068744,Puma,,WA,299000.0,1,299000.0,89700.0,89700.0,209300.0,0.0,0.0,0.0,0.0,0.357228,0.0,209300.0,0.0,0.0
1,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,169582202791437,2312000024580,0000082690,0900000053740,Puma,,WA,259000.0,1,259000.0,77700.0,77700.0,181300.0,81666.0,0.0,0.0,81666.0,0.309438,0.0,181300.0,0.0,0.0
2,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,170079545324398,2312000024654,0000083042,0900000067716,Puma,,WA,279000.0,1,279000.0,83700.0,83700.0,195300.0,0.0,0.0,0.0,0.0,0.333333,0.0,195300.0,0.0,0.0
3,mgl,C0075|OUTLET SZ BG JUNCTION SURABAYA,1202,C0075,2024-06-01 21:08:24,2024-06-01 21:59:23,2024-06-01,21,08,171725090438770,171725090478432,171725090442237,1636.0,999,OOFL010624120200043,True,6,5,5,852600.0,400000.0,452600.0,452600.0,0,0.0,452600.0,0,None,None,170167960108327,2312000018537,0000057544,3900000005265,Tres Jolie,,WA,129900.0,1,129900.0,0.0,0.0,129900.0,55293.0,0.0,0.0,55293.0,0.287008,0.0,129900.0,0.0,0.0
4,mgl,C0075|OUTLET SZ BG JUNCTION SURABAYA,1202,C0075,2024-06-01 21:08:24,2024-06-01 21:59:23,2024-06-01,21,08,171725090438770,171725090478432,171725090442237,1636.0,999,OOFL010624120200043,True,6,5,5,852600.0,400000.0,452600.0,452600.0,0,0.0,452600.0,0,None,None,170167958818818,2312000018539,0000057553,3900000004152,Tres Jolie,,WA,119900.0,1,119900.0,0.0,0.0,119900.0,41636.0,0.0,0.0,41636.0,0.264914,0.0,119900.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35192,mgl,C0006|OUTLET SZ REST AREA PENDOPO 456A SEMARANG,1218,C0006,2024-06-30 08:32:56,2024-06-30 21:58:59,2024-06-30,08,32,171971117659605,171971117689507,171971117675207,3008.0,999,OOFL300624121800002,True,6,1,1,66900.0,0.0,66900.0,66900.0,0,0.0,66900.0,350,[SZ] KS SEKAWAN,[SZ] KS SEKAWAN,169528585156440,2312000039757,0000167101,4100000000010,Sekawan,,WA,66900.0,1,66900.0,0.0,0.0,66900.0,0.0,0.0,0.0,0.0,1.000000,0.0,66900.0,0.0,0.0
35193,mgl,C0005|OUTLET SZ REST AREA KM 72A PURWAKARTA,1216,C0005,2024-06-30 08:34:21,2024-06-30 21:56:40,2024-06-30,08,34,171971126192848,171971126159217,171971126186488,1662.0,999,OOFL300624121600001,True,6,2,2,529800.0,52980.0,476820.0,476820.0,0,0.0,476820.0,2729,[SZ] Add 10% for minimum purchase 500k Inhouse...,[SZ] Add 10% for minimum purchase 500k Inhouse...,169097102191919,2312000018264,0000056201,0500000003594,Due,,WA,229900.0,1,229900.0,22990.0,22990.0,206910.0,0.0,0.0,0.0,0.0,0.433937,0.0,206910.0,0.0,0.0
35194,mgl,C0005|OUTLET SZ REST AREA KM 72A PURWAKARTA,1216,C0005,2024-06-30 08:34:21,2024-06-30 21:56:40,2024-06-30,08,34,171971126192848,171971126159217,171971126186488,1662.0,999,OOFL300624121600001,True,6,2,2,529800.0,52980.0,476820.0,476820.0,0,0.0,476820.0,2729,[SZ] Add 10% for minimum purchase 500k Inhouse...,[SZ] Add 10% for minimum purchase 500k Inhouse...,171083892360226,2403000001615,0000173523,0800001735235,Stock Lot,,WA,299900.0,1,299900.0,29990.0,29990.0,269910.0,148379.0,0.0,0.0,148379.0,0.566063,0.0,269910.0,0.0,0.0
35195,mgl,C0026|OUTLET PM REST AREA KM 754 SIDOARJO,1198,C0026,2024-06-30 08:36:31,2024-06-30 22:48:18,2024-06-30,08,36,171971139161766,171971139110287,171971139182706,2713.0,999,OOFL300624119800001,True,6,1,1,999000.0,299700.0,699300.0,699300.0,0,0.0,699300.0,2172,[PM] Puma Outlet Disc 30%,[PM] Puma Outlet Disc 30%,169092120268766,2312000021360,0000068729,0900000021527,Puma,,WA,999000.0,1,999000.0,299700.0,299700.0,699300.0,0.0,0.0,0.0,0.0,1.000000,0.0,699300.0,0.0,0.0
35196,mgl,C0006|OUTLET SZ REST AREA PENDOPO 456A SEMARANG,1218,C0006,2024-06-30 08:39:17,2024-06-30 21:58:59,2024-06-30,08,39,171971155770321,171971155711843,171971155788606,3008.0,999,OOFL300624121800003,True,6,1,1,299900.0,120000.0,179900.0,179900.0,0,0.0,179900.0,2581,[SZ] Minimal Update Price June,[SZ] Minimal Update Price June,169097957888366,2312000014128,0000139132,8990400013040,Minimal,,CSG,299900.0,1,299900.0,120000.0,120000.0,179900.0,0.0,0.0,0.0,0.0,1.000000,0.0,179900.0,0.0,0.0

In [3]:
extractor = S3Extractor(bucket_name="mega-dev-lake")

In [4]:
df_order = extractor.extractDataOrderTransactionIndie(
    prefix="RawData/indie_on_develop/",
    company="mgl",
    channel="showroom",
    source="orders",
    year="2024",
    month="06",
)

In [5]:
df_order[df_order['order_number'] == 'OOFL250624119600006']

,order_id,order_number,order_total_product,order_total_quantity,order_subtotal,order_total_product_compliment,order_total_transaction_compliment,order_total_compliment,order_discount,order_total,order_cashback,order_tax,order_delivery_cost,order_delivery_discount,order_store_fee,order_status,order_group_order_ref,order_ismanual,order_isrecord,order_issettled,order_ispromotionhasrelation,order_isreadyorder,time_created,time_modified,time_settled,time_max_process,time_max_process_finish,time_process_finish,time_max_delivery,time_delivered,time_max_finished,time_finished,promotionData,invoice_id,transaction_id,customer_id,employment_id,store_branch_id,store_branch_name,store_branch_extcode,store_branch_description,store_branch_time_difference,store_branch_channel,store_branch_company,transaction_source_id,transaction_source_type,transaction_source_name,transaction_source_code,order_product_id,order_product_quantity,order_product_subtotal,order_product_discount,order_product_total,order_product_tax,order_product_type,order_product_cashback,order_product_store_fee,order_product_status,order_product_customer_note,order_product_promotion_id,order_product_promotion_value,order_product_promotion_status,order_product_promotion_isclearence,order_product_promotion_iscustompromotion,promotion_id,promotion_title,promotion_type,promotion_barcode,promotion_creator,promotion_description,compliment_id,compliment_value,compliment_note,compliment_type,compliment_percentage,compliment_creator,product_id,product_barcode,product_base_price,product_price,pull_status,pull_date,ref_return_order_id,ref_return_order_number,ref_return_transaction_id,ref_return_transaction_number,dataareaid
550,171930425695647,OOFL250624119600006,3,3,1737000.0,0.0,0.0,0.0,513200.0,1223800.0,0.0,121278.0,0.0,0.0,0.0,6,None,False,False,True,True,True,2024-06-25 15:30:56,2024-06-25 22:01:09,2024-06-25 22:01:09,2024-06-29 15:30:54,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,None,171930425669473,171930425659740,999,3471.0,1196,C0018|OUTLET PM REST AREA KM 379A BATANG,C0018,20084|CS1743|C0018,0,SHOWROOM,PT. Mitrelindo Global,1,1,Offline Store,OFL,8279187,1,259000.0,77700.0,181300.0,0.0,1,0.0,0.0,6,None,6920856.0,77700.0,1.0,False,False,2172.0,[PM] Puma Outlet Disc 30%,1.0,0.0,1.0,[PM] Puma Outlet Disc 30%,0.0,0.0,None,0.0,0.0,0.0,170289864903984,0900000076664,81666.0,259000.0,latest,2024-07-01 21:37:21,0.0,None,0.0,None,mgl
551,171930425695647,OOFL250624119600006,3,3,1737000.0,0.0,0.0,0.0,513200.0,1223800.0,0.0,121278.0,0.0,0.0,0.0,6,None,False,False,True,True,True,2024-06-25 15:30:56,2024-06-25 22:01:09,2024-06-25 22:01:09,2024-06-29 15:30:54,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,None,171930425669473,171930425659740,999,3471.0,1196,C0018|OUTLET PM REST AREA KM 379A BATANG,C0018,20084|CS1743|C0018,0,SHOWROOM,PT. Mitrelindo Global,1,1,Offline Store,OFL,8279188,1,1399000.0,419700.0,979300.0,0.0,1,0.0,0.0,6,None,6920857.0,419700.0,1.0,False,False,2172.0,[PM] Puma Outlet Disc 30%,1.0,0.0,1.0,[PM] Puma Outlet Disc 30%,0.0,0.0,None,0.0,0.0,0.0,169092420519525,0900000032363,693198.0,1399000.0,latest,2024-07-01 21:37:21,0.0,None,0.0,None,mgl
552,171930425695647,OOFL250624119600006,3,3,1737000.0,0.0,0.0,0.0,513200.0,1223800.0,0.0,121278.0,0.0,0.0,0.0,6,None,False,False,True,True,True,2024-06-25 15:30:56,2024-06-25 22:01:09,2024-06-25 22:01:09,2024-06-29 15:30:54,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,2024-06-25 15:30:56,None,171930425669473,171930425659740,999,3471.0,1196,C0018|OUTLET PM REST AREA KM 379A BATANG,C0018,20084|CS1743|C0018,0,SHOWROOM,PT. Mitrelindo Global,1,1,Offline Store,OFL,8279189,1,79000.0,15800.0,63200.0,0.0,1,0.0,0.0,6,None,6920858.0,15800.0,1.0,False,False,2170.0,[PM] Puma Outlet Disc 20%,1.0,0.0,1.0,[PM] Puma Outlet Disc 20%,0.0,0.0,None,0.0,0.0,0.0,170295817564713,0900000075971,37364.0,79000.0,latest,2024-07-01 21:37:21,0.0,None,0.0,None,mgl

In [3]:
df = etl.run()

In [6]:
df

,data_area_id,store_branch_name,store_branch_id,store_code,time_created,time_modified,order_create_date,order_create_hour,order_create_minute,order_id,transaction_id,invoice_id,employment_id,customer_id,order_number,order_issettled,order_status,order_total_product,order_total_quantity,order_subtotal,order_discount,order_total,order_transaction_price,order_voucher_payment,order_return_payment,order_cust_payment,promotion_id,promotion_title,promotion_description,product_id,product_item_id,product_variant_number,product_barcode,product_brand,product_sub_brand,product_item_model_group,product_price,product_quantity,product_subtotal,product_promotion_value,product_discount,product_transaction_price,product_cost,product_margin,product_cost_of_margin,product_total_cost,product_payment_contribution,product_voucher_payment,product_cust_payment,product_return_value,product_invoice_discount
0,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,170079543365488,2312000024734,0000083380,0900000068744,Puma,,WA,299000.0,1,299000.0,89700.0,89700.0,209300.0,113198.0,0.0,0.0,113198.0,0.357228,0.0,209300.0,0.0,0.0
1,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,169582202791437,2312000024580,0000082690,0900000053740,Puma,,WA,259000.0,1,259000.0,77700.0,77700.0,181300.0,81666.0,0.0,0.0,81666.0,0.309438,0.0,181300.0,0.0,0.0
2,mgl,C0001|SHOWROOM PM EMPORIUM PLUIT,1221,C0001,2024-06-01 21:06:50,2024-06-01 22:14:44,2024-06-01,21,06,171725081041925,171725081064956,171725081077164,3298.0,999,OOFL010624122100006,True,6,3,3,837000.0,251100.0,585900.0,585900.0,0,0.0,585900.0,2126,[PM] Puma Discount - MONO,[PM] Puma Discount - MONO,170079545324398,2312000024654,0000083042,0900000067716,Puma,,WA,279000.0,1,279000.0,83700.0,83700.0,195300.0,110045.0,0.0,0.0,110045.0,0.333333,0.0,195300.0,0.0,0.0
3,mgl,C0075|OUTLET SZ BG JUNCTION SURABAYA,1202,C0075,2024-06-01 21:08:24,2024-06-01 21:59:23,2024-06-01,21,08,171725090438770,171725090478432,171725090442237,1636.0,999,OOFL010624120200043,True,6,5,5,852600.0,400000.0,452600.0,452600.0,0,0.0,452600.0,0,None,None,170167960108327,2312000018537,0000057544,3900000005265,Tres Jolie,,WA,129900.0,1,129900.0,0.0,0.0,129900.0,55293.0,0.0,0.0,55293.0,0.287008,0.0,129900.0,0.0,0.0
4,mgl,C0075|OUTLET SZ BG JUNCTION SURABAYA,1202,C0075,2024-06-01 21:08:24,2024-06-01 21:59:23,2024-06-01,21,08,171725090438770,171725090478432,171725090442237,1636.0,999,OOFL010624120200043,True,6,5,5,852600.0,400000.0,452600.0,452600.0,0,0.0,452600.0,0,None,None,170167958818818,2312000018539,0000057553,3900000004152,Tres Jolie,,WA,119900.0,1,119900.0,0.0,0.0,119900.0,41636.0,0.0,0.0,41636.0,0.264914,0.0,119900.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35192,mgl,C0006|OUTLET SZ REST AREA PENDOPO 456A SEMARANG,1218,C0006,2024-06-30 08:32:56,2024-06-30 21:58:59,2024-06-30,08,32,171971117659605,171971117689507,171971117675207,3008.0,999,OOFL300624121800002,True,6,1,1,66900.0,0.0,66900.0,66900.0,0,0.0,66900.0,350,[SZ] KS SEKAWAN,[SZ] KS SEKAWAN,169528585156440,2312000039757,0000167101,4100000000010,Sekawan,,WA,66900.0,1,66900.0,0.0,0.0,66900.0,0.0,0.0,0.0,0.0,1.000000,0.0,66900.0,0.0,0.0
35193,mgl,C0005|OUTLET SZ REST AREA KM 72A PURWAKARTA,1216,C0005,2024-06-30 08:34:21,2024-06-30 21:56:40,2024-06-30,08,34,171971126192848,171971126159217,171971126186488,1662.0,999,OOFL300624121600001,True,6,2,2,529800.0,52980.0,476820.0,476820.0,0,0.0,476820.0,2729,[SZ] Add 10% for minimum purchase 500k Inhouse...,[SZ] Add 10% for minimum purchase 500k Inhouse...,169097102191919,2312000018264,0000056201,0500000003594,Due,,WA,229900.0,1,229900.0,22990.0,22990.0,206910.0,0.0,0.0,0.0,0.0,0.433937,0.0,206910.0,0.0,0.0
35194,mgl,C0005|OUTLET SZ REST AREA KM 72A PURWAKARTA,1216,C0005,2024-06-30 08:34:21,2024-06-30 21:56:40,2024-06-30,08,34,171971126192848,171971126159217,171971126186488,1662.0,999,OOFL300624121600001,True,6,2,2,529800.0,52980.0,476820.0,476820.0,0,0.0,476820.0,2729,[SZ] Add 10% for minimum purchase 500k Inhouse...,[SZ] Add 10% for minimum purchase 500k Inhouse...,171083892360226,2403000001615,0000173523,0800001735235,Stock Lot,,WA,299900.0,1,299900.0,29990.0,29990.0,269910.0,148379.0,0.0,0.0,148379.0,0.566063,0.0,269910.0,0.0,0.0
35195,mgl,C0026|OUTLET PM REST AREA KM 754 SIDOARJO,1198,C0026,2024-06-30 08:36:31,2024-06-30 22:48:18,2024-06-30,08,36,171971139161766,171971139110287,171971139182706,2713.0,999,OOFL300624119800001,True,6,1,1,999000.0,299700.0,699300.0,699300.0,0,0.0,699300.0,2172,[PM] Puma Outlet Disc 30%,[PM] Puma Outlet Disc 30%,169092120268766,2312000021360,0000068729,0900000021527,Puma,,WA,999000.0,1,999000.0,299700.0,299700.0,699300.0,519797.0,0.0,0.0,519797.0,1.000000,0.0,699300.0,0.0,0.0
35196,mgl,C0006|OUTLET SZ REST AREA PENDOPO 456A SEMARANG,1218,C0006,2024-06-30 08:39:17,2024-06-30 21:58:59,2024-06-30,08,39,171971155770321,171971155711843,171971155788606,3008.0,999,OOFL300624121800003,True,6,1,1,299900.0,120000.0,179900.0,179900.0,0,0.0,179900.0,2581,[SZ] Minimal Update Price June,[SZ] Minimal Update Price June,169097957888366,2312000014128,0000139132,8990400013040,Minimal,,CSG,299900.0,1,299900.0,120000.0,120000.0,179900.0,0.0,0.0,0.0,0.0,1.000000,0.0,179900.0,0.0,0.0

In [14]:
df[df["order_number"] == "OOFL1506241570700034"]

,data_area_id,store_branch_name,store_branch_id,store_code,time_created,time_modified,order_create_date,order_create_hour,order_create_minute,order_id,transaction_id,invoice_id,employment_id,customer_id,order_number,order_issettled,order_status,order_total_product,order_total_quantity,order_subtotal,order_discount,order_total,order_transaction_price,order_voucher_payment,order_return_payment,order_cust_payment,promotion_id,promotion_title,promotion_description,product_id,product_item_id,product_variant_number,product_barcode,product_brand,product_sub_brand,product_item_model_group,product_price,product_quantity,product_subtotal,product_promotion_value,product_discount,product_transaction_price,product_cost,product_margin,product_cost_of_margin,product_total_cost,product_payment_contribution,product_voucher_payment,product_cust_payment,product_return_value,product_invoice_discount
15013,mgl,C0152|BAZAAR SZ LIVING WORLD KOTAWISATA,15707,C0152,2024-06-15 20:17:06,2024-06-15 22:16:17,2024-06-15,20,17,171845742602107,171845742667143,171845742661534,3285.0,999,OOFL1506241570700034,True,6,2,2,132900.0,30000.0,102900.0,102900.0,0,0.0,102900.0,2520,{SZ] Denim Korea Markdown per 1 March 2024,{SZ] Denim Korea Markdown per 1 March 2024,170394391929217,2312000061530,0000154679,9900000004965,Stock Lot,,WA,129900.0,1,129900.0,30000.0,30000.0,99900.0,39928.0,0.0,0.0,39928.0,0.970845,0.0,99900.0,0.0,0.0
15014,mgl,C0152|BAZAAR SZ LIVING WORLD KOTAWISATA,15707,C0152,2024-06-15 20:17:06,2024-06-15 22:16:17,2024-06-15,20,17,171845742602107,171845742667143,171845742661534,3285.0,999,OOFL1506241570700034,True,6,2,2,132900.0,30000.0,102900.0,102900.0,0,0.0,102900.0,0,None,None,169117596048769,2312000029357,0000100721,2000000129359,Stock Lot,,WA,3000.0,1,3000.0,0.0,0.0,3000.0,1975.0,0.0,0.0,1975.0,0.029155,0.0,3000.0,0.0,0.0